### PR TITLE
CSS + misc changes

### PR DESCRIPTION
**Pull request by Quelklef**
Made the about page not have huge text
Added a tile to the layout html

### CODE REVIEW

**Comment by samm81** [comment]
please compile the sass to css and commit the css
I don't want another dependency in the project

**Comment by samm81** [comment]
also please squash all commits into one commit

**Comment by samm81** [comment]
also I updated master so make sure merge that in

**Comment by Quelklef** [comment]
Will do soon. What's wrong with many commits _if_ I'm working alone?

**Comment by samm81** [comment]
see [this](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

Once it's merged into master all these commits show up on the master timeline. There is no need to have "added pyenv" followed by "removed pyenv" in the commit history. All of these changes should really be compressed to one "added custom css" commit.

**Comment by samm81** [comment]
please remove readme, I will add it when I am ready

**Comment by samm81** [comment]
Again, please compile the sass and commit the css file rather than the sass. I don't want to add another dependency.

**Comment by Quelklef** [comment]
Didn't see about the sass. Is there some way to retroactively compress these commits? Also, anything else I need to change before I commit?

**Comment by Quelklef** [comment]
Oh, and the delete / create about.html was only because I was doing it on the Github site rather than on Linux.

**Comment by samm81** [comment]
see the link I posted (https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

**Comment by samm81** [comment]
still need to commit css rather than sass

**Comment by Quelklef** [comment]
I have that done locally. Don't want to commit till I'm sure there's nothing else to do.

**Comment by samm81** [comment]
This looks great! I'm gonna go ahead and merge this into master - however I'm not going to send it to production. It would be great if you would optimize it for mobile - as most users would be accessing it through the mobile interface rather than the web one. A couple of issues that occur right now are that there's not enough room in the top bar causing a break, that the bottom line is doubled up, and that on the food selection page the names of foods are double-spaced.

**Pull request merged**
